"""Consolidates the three scenario reports in `outputs/scenarios/` into one
cross-scenario summary — `summary.json`, `summary.csv`, and `summary.md`.

This runs on the already-written JSON reports, so it needs no dataset, no
model, and no GPU, and takes under a second. That is the point: the
scenario tables published in the research document are generated by this
script, so a reviewer can regenerate and check every published figure
against the raw evidence without re-running the multi-hour simulations
that produced it.

Run:
    python -m src.scenarios.summarise [--output-dir outputs] [--scenario name ...]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Optional

from src.reporting import write_csv
from src.scenarios import metrics

SCENARIOS = ("disconnection", "class_addition", "distribution_shift")

# Preference order for the two-or-three metrics the published tables quote;
# whichever of these a report actually contains are used, so a report from
# an older run (crop/disease accuracy only) and one from the current code
# (which also records pair_accuracy and macro-F1s) both summarise cleanly.
HEADLINE_METRICS = ("crop_accuracy", "disease_accuracy", "pair_accuracy")

# config keys that name the round a scenario's disruption begins, used only
# for reports written before `disruption_start_round` was recorded directly.
_DISRUPTION_ROUND_KEYS = ("disconnect_round", "inject_round", "shift_round")


def disruption_rounds(report: dict) -> tuple[int, int]:
    """(start, end) round indices for a report's disruption window. Reports
    written by the current harness carry these directly; for older ones they
    are recovered from the scenario config, then from the first recorded
    event, so archived evidence still summarises without hand-editing.
    """
    if "disruption_start_round" in report:
        return report["disruption_start_round"], report.get("disruption_end_round", report["disruption_start_round"])

    config = report.get("config", {})
    start = next((config[k] for k in _DISRUPTION_ROUND_KEYS if k in config), None)
    if start is None:
        events = [r for r in report.get("rounds", []) if r.get("events")]
        start = events[0]["round_idx"] if events else 0
    return start, config.get("reconnect_round", start)


def headline_metrics(report: dict) -> list[str]:
    target = report.get("target_node", "")
    rounds = report.get("rounds", [])
    if not rounds:
        return []
    available = set(metrics.scalar_eval(rounds[0], "mesh_eval", target))
    return [m for m in HEADLINE_METRICS if m in available]


def _fmt_pct(value: Optional[float]) -> str:
    return "—" if value is None else f"{value * 100:.2f}%"


def _fmt_pp(value: Optional[float]) -> str:
    return "—" if value is None else f"{value * 100:+.2f}pp"


def _fmt_sci(value: Optional[float]) -> str:
    return "—" if value is None else f"{value:.2e}"


def _event_label(round_: dict) -> str:
    """A plain-ASCII description of what the harness injected this round, or
    "" for an undisturbed round. Kept ASCII because this string also lands in
    the CSV exports; the markdown formatter substitutes a dash for "".
    """
    if not round_.get("events"):
        return ""
    return "; ".join(
        f"{e['event_type']} ({e['node_id']})" + (f" {e['details']}" if e.get("details") else "")
        for e in round_["events"]
    )


def per_round_rows(report: dict) -> list[dict]:
    """One row per round: what happened, what it cost, and how the disrupted
    node plus the mesh as a whole fared against the local-only arm.
    """
    target = report.get("target_node", "")
    rows = []
    for round_ in report.get("rounds", []):
        gain = round_.get("collaboration_gain", {})
        mesh_target = metrics.scalar_eval(round_, "mesh_eval", target)
        base_target = metrics.scalar_eval(round_, "baseline_eval", target)
        row = {
            "scenario": report.get("scenario", ""),
            "round_idx": round_["round_idx"],
            "event": _event_label(round_),
            "active_nodes": len(round_.get("active_nodes", [])),
            "bytes_exchanged": round_.get("total_bytes_exchanged", 0),
            "communication_energy_j": round_.get("communication_energy_j", 0.0),
            "baseline_compute_energy_kwh": round_.get("baseline_compute_energy_kwh", 0.0),
            "mesh_compute_energy_kwh": round_.get("mesh_compute_energy_kwh", 0.0),
        }
        for m in headline_metrics(report):
            row[f"target_mesh_{m}"] = mesh_target.get(m)
            row[f"target_baseline_{m}"] = base_target.get(m)
            row[f"target_advantage_{m}"] = (
                None if m not in mesh_target or m not in base_target else mesh_target[m] - base_target[m]
            )
            row[f"macro_gain_{m}"] = gain.get("macro_gain", {}).get(m)
            row[f"worst_node_gain_{m}"] = gain.get("worst_node_gain", {}).get(m)
        rows.append(row)
    return rows


def summarise(report: dict) -> dict:
    """One scenario's derived-metric block, recomputed from its rounds so it
    is identical whether the report was written before or after these
    metrics were added to the harness.
    """
    start, end = disruption_rounds(report)
    derived = metrics.summarise_scenario(report, start)
    return {
        "scenario": report.get("scenario", ""),
        "target_node": report.get("target_node", ""),
        "config": report.get("config", {}),
        "provenance": report.get("provenance", {}),
        "disruption_start_round": start,
        "disruption_end_round": end,
        "num_rounds": len(report.get("rounds", [])),
        "recovery_round_mesh": report.get("summary", {}).get("recovery_round_mesh"),
        "recovery_round_baseline": report.get("summary", {}).get("recovery_round_baseline"),
        **derived,
    }


def _cross_scenario_row(s: dict) -> dict:
    eff = s["efficiency"]
    energy = s["energy"]
    row = {
        "scenario": s["scenario"],
        "target_node": s["target_node"],
        "num_rounds": s["num_rounds"],
        "disruption_start_round": s["disruption_start_round"],
        "recovery_round_mesh": s["recovery_round_mesh"],
        "recovery_round_baseline": s["recovery_round_baseline"],
        "total_bytes_exchanged": energy["total_bytes_exchanged"],
        "total_communication_energy_j": energy["total_communication_energy_j"],
        "total_baseline_compute_energy_kwh": energy["total_baseline_compute_energy_kwh"],
        "total_mesh_compute_energy_kwh": energy["total_mesh_compute_energy_kwh"],
        "additional_energy_j": energy["additional_energy_j"],
    }
    for m in HEADLINE_METRICS:
        for label, block in (
            ("final_macro_gain", eff["final_round_macro_gain"]),
            ("adaptation_gain", s["adaptation"]["adaptation_gain"]),
            ("pre_disruption_advantage", s["adaptation"]["pre_disruption_advantage"]),
            ("advantage_delta", s["adaptation"]["advantage_delta"] or {}),
            ("retention_gain", s["retention"]["retention_gain"] or {}),
            ("gain_per_joule", eff["gain_per_joule"] or {}),
            ("gain_per_additional_joule", eff["gain_per_additional_joule"] or {}),
            ("gain_per_byte", eff["gain_per_byte"] or {}),
        ):
            if m in block:
                row[f"{label}_{m}"] = block[m]
    return row


def _markdown(summaries: list[dict], reports: dict[str, dict]) -> str:
    lines = [
        "# Scenario-driven demonstration — consolidated results",
        "",
        "Generated by `python -m src.scenarios.summarise` from the JSON reports in",
        "`outputs/scenarios/`. Every figure below is recomputed from those reports'",
        "per-round records, so it can be checked against the raw evidence directly.",
        "",
        "## Cross-scenario summary",
        "",
        "| Scenario | Target node | Disruption round | Recovery (mesh) | Recovery (local-only) | "
        "Adaptation gain, crop / disease | Retention gain, crop / disease | "
        "Final macro gain, crop / disease |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for s in summaries:
        adapt = s["adaptation"]["adaptation_gain"]
        retain = s["retention"]["retention_gain"] or {}
        final = s["efficiency"]["final_round_macro_gain"]
        pair = lambda d: f"{_fmt_pp(d.get('crop_accuracy'))} / {_fmt_pp(d.get('disease_accuracy'))}"  # noqa: E731
        lines.append(
            f"| {s['scenario']} | {s['target_node']} | {s['disruption_start_round']} | "
            f"{s['recovery_round_mesh']} | {s['recovery_round_baseline']} | "
            f"{pair(adapt)} | {pair(retain)} | {pair(final)} |"
        )

    lines += [
        "",
        "## Cost of collaboration, and gain per unit of it",
        "",
        "| Scenario | Bytes exchanged | Communication energy (J) | Local-only compute (kWh) | "
        "Mesh compute (kWh) | Additional energy (J) | gain_per_joule, crop / disease | "
        "gain_per_additional_joule, crop / disease | gain_per_byte, crop / disease |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for s in summaries:
        e, eff = s["energy"], s["efficiency"]
        sci = lambda d: (  # noqa: E731
            f"{_fmt_sci((d or {}).get('crop_accuracy'))} / {_fmt_sci((d or {}).get('disease_accuracy'))}"
        )
        lines.append(
            f"| {s['scenario']} | {e['total_bytes_exchanged']:,} | "
            f"{e['total_communication_energy_j']:.2f} | {e['total_baseline_compute_energy_kwh']:.6f} | "
            f"{e['total_mesh_compute_energy_kwh']:.6f} | {e['additional_energy_j']:,.0f} | "
            f"{sci(eff['gain_per_joule'])} | {sci(eff['gain_per_additional_joule'])} | "
            f"{sci(eff['gain_per_byte'])} |"
        )

    for s in summaries:
        name = s["scenario"]
        report = reports[name]
        lines += [
            "",
            f"## Per-round detail — {name} (target {s['target_node']})",
            "",
            "| Round | Event | Active nodes | Bytes | Comm. (J) | Target mesh crop / disease | "
            "Target local-only crop / disease | Macro gain crop / disease | Worst-node gain crop / disease |",
            "|---|---|---|---|---|---|---|---|---|",
        ]
        for row in per_round_rows(report):
            lines.append(
                f"| {row['round_idx']} | {row['event'] or '—'} | {row['active_nodes']} | "
                f"{row['bytes_exchanged']:,} | {row['communication_energy_j']:.2f} | "
                f"{_fmt_pct(row.get('target_mesh_crop_accuracy'))} / "
                f"{_fmt_pct(row.get('target_mesh_disease_accuracy'))} | "
                f"{_fmt_pct(row.get('target_baseline_crop_accuracy'))} / "
                f"{_fmt_pct(row.get('target_baseline_disease_accuracy'))} | "
                f"{_fmt_pp(row.get('macro_gain_crop_accuracy'))} / "
                f"{_fmt_pp(row.get('macro_gain_disease_accuracy'))} | "
                f"{_fmt_pp(row.get('worst_node_gain_crop_accuracy'))} / "
                f"{_fmt_pp(row.get('worst_node_gain_disease_accuracy'))} |"
            )

    lines += ["", "## Metric definitions", "", summaries[0]["efficiency"]["formula"] if summaries else "", ""]
    return "\n".join(lines)


def build_summary(output_dir: Path, scenario_names: tuple[str, ...] = SCENARIOS) -> dict:
    scenarios_dir = output_dir / "scenarios"
    reports: dict[str, dict] = {}
    missing: list[str] = []
    for name in scenario_names:
        path = scenarios_dir / f"{name}.json"
        if path.exists():
            reports[name] = json.loads(path.read_text())
        else:
            missing.append(name)

    if not reports:
        raise FileNotFoundError(
            f"No scenario reports found in {scenarios_dir} — run 'python -m src.scenarios.run_all' first "
            f"(looked for: {', '.join(f'{n}.json' for n in scenario_names)})"
        )

    summaries = [summarise(reports[name]) for name in scenario_names if name in reports]
    return {
        "scenarios_summarised": list(reports),
        "scenarios_missing": missing,
        "per_scenario": summaries,
        "cross_scenario_table": [_cross_scenario_row(s) for s in summaries],
        "per_round_table": [row for name in reports for row in per_round_rows(reports[name])],
        "markdown": _markdown(summaries, reports),
    }


def write_summary(output_dir: Path, scenario_names: tuple[str, ...] = SCENARIOS) -> Path:
    summary = build_summary(output_dir, scenario_names)
    scenarios_dir = output_dir / "scenarios"
    scenarios_dir.mkdir(parents=True, exist_ok=True)

    json_path = scenarios_dir / "summary.json"
    json_path.write_text(json.dumps({k: v for k, v in summary.items() if k != "markdown"}, indent=2))
    (scenarios_dir / "summary.md").write_text(summary["markdown"], encoding="utf-8")
    write_csv(summary["cross_scenario_table"], scenarios_dir / "summary.csv")
    write_csv(summary["per_round_table"], scenarios_dir / "summary_per_round.csv")

    if summary["scenarios_missing"]:
        print(f"WARNING: no report found for {', '.join(summary['scenarios_missing'])} — summarised the rest")
    return json_path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", default="outputs")
    parser.add_argument(
        "--scenario", action="append", choices=SCENARIOS,
        help="summarise only this scenario (repeatable); defaults to all three",
    )
    args = parser.parse_args()
    names = tuple(args.scenario) if args.scenario else SCENARIOS
    json_path = write_summary(Path(args.output_dir), names)
    print(f"Wrote {json_path}, {json_path.with_name('summary.md')}, {json_path.with_name('summary.csv')}")


if __name__ == "__main__":
    main()
